Feature/co 1466 implement unit tests
osu-mist/directory-api pull request #39
Opened 2019-10-04 20:42 UTC by kalcicd

2019-10-17 23:22 UTC, kalcicd commented
Do you think that any more tests are required for the endpoint functions? If not, I'll remove the endpoint tests from the forEach loops. Also, is there merit to writing a test for the valueOperations helper?

2019-10-18 00:25 UTC, Ruefa requested changes
I got an error when trying to run without a config file. I did the same thing while writing the onbase unit tests. See how I stubbed config [here](https://github.com/osu-mist/onbase-api/blob/master/src/tests/unit/onbase-dao.test.js). It also looks like the serializer tests are missing.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
> +  if (option === 'getDirectories') {
There's a lot of repeated code in here. Here's how I would reduce it.
```
proxyquireObject.util.promisify = () => sinon.stub().resolves({
      on: (type, listener) => {
        if (type === option) {
          listener(option === 'searchEntry' ? { object: {} } : undefined);
        }
      },
    });
```
You can then pass in 'done' and 'searchEntry' for option and you won't need the if statement at all.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
> +    const testCaseList = [singleResult];
Don't need to loop if there is only one test case.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
> +    const testCaseList = [multiResult];
Same as above. one test case doesn't need a loop.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
> +    });
These two cases are near identical. I would make a helper function that takes the differences as parameters. Having the serializer stub return `testCase` which is the same as `expectedResult` pretty much nullifies your tests. Try setting it to `returnsArg(0)`, I don't think that will break your tests. Then you can just always stub both serializers in the helper function and it won't need to be an additional parameter. Checkout the helper functions I wrote in [onbase unit tests](https://github.com/osu-mist/onbase-api/blob/master/src/tests/unit/onbase-dao.test.js) for inspiration.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
> +import proxyquire from 'proxyquire';
imports should be in alphabetical order based on the package/file name. If going by file names (the second section of imports, line 7-8) then you include the directory prefix i.e. the whole `'api/v2/serializers/directory-serializer'` would be included in the alphabetization. `proxyquire` is the only one out of the place here.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> +
Remove this extra line

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> +// import { clear } from 'winston';
remove comment

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> +import sinon from 'sinon';
Alphabetize imports. See above comment.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> +import * as conn from 'api/v2/db/ldap/connection';
local imports should be separate from package imports. Add a line here between conn and lodash similar to directory-dao-test.js.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> + * @param {object} testCase The testcase that becomes the return value of client.promiseSearch
Looks like this param is no longer included.

2019-10-18 00:25 UTC, Ruefa commented on src/tests/unit/test-util.js
> +
This file isn't used anywhere. I'm assuming they are for the serializer tests which are also missing.

2019-10-25 19:24 UTC, Ruefa requested changes

2019-10-25 19:24 UTC, Ruefa commented on src/api/v2/serializers/directory-serializer.js
> +
remove extra line

2019-10-25 19:24 UTC, Ruefa commented on src/tests/unit/directory-dao.test.js
removed extra line

2019-10-25 19:24 UTC, Ruefa commented on src/tests/unit/directory-serializer.test.js
> +import chai from 'chai';
You should take a look at some of the test helpers [here](https://github.com/osu-mist/game-curator-api/blob/master/tests/unit/test-helpers.js#L45). Almost any change to the swagger document will break your tests. You should be able to copy over those helpers without making too many changes.

2019-10-29 16:04 UTC, Ruefa approved these changes
Fix the 2 small issues then you can merge.

2019-10-29 16:04 UTC, Ruefa commented on src/tests/unit/test-utils.js
> + * @param {*} resourceKey The id of the resource.
These params should be strings

2019-10-29 16:04 UTC, Ruefa commented on src/tests/unit/test-utils.js
> +
remove extra line

2019-10-31 21:12 UTC, merged